import { Lexend } from 'next/font/google';
import { oceanwide, fira_code } from '@/fonts';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const font = Lexend({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${oceanwide.variable} ${fira_code.variable}`}>
      <body className={`${font.className} overflow-y-scroll no-scrollbar`}>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
