import { Lexend } from 'next/font/google';
import { oceanwide, fira_code, nt_adventure,lexend } from '@/fonts';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

const font = Lexend({ subsets: ['latin'] });

export const metadata = {
  title: 'WeFrameTech',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/logo.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${oceanwide.variable} ${fira_code.variable} ${nt_adventure.variable} ${lexend.variable}`}
    >
      <body className={`${font.className} overflow-y-scroll no-scrollbar`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
